[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nebulous_world = "7AAwB8aHgmuz9yzYdo6gKjZRx5KkjePYHyuJEmrcRXgX"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"

[hooks]
